Repository ergebnis/php-package-template, pull requests merged in 2019-12, with the labels that each got.

#180 Fix: No need to use which
  .github/workflows/continuous-integration.yml
Labels: bug

#181 Fix: Update localheinz/composer-require-checker-action
  .github/workflows/continuous-integration.yml
  Makefile
Labels: bug

#182 Enhancement: Require phpstan/extension-installer
  composer.json
  composer.lock
  phpstan.neon
Labels: enhancement

#183 Fix: Do not include bleedingEdge.neon anymore
  phpstan.neon
Labels: bug

#185 Fix: Remove non-applicable configuration
  phpstan.neon
Labels: bug

#184 Bump infection/infection from 0.14.2 to 0.15.0
  composer.json
  composer.lock
Labels: enhancement

#186 Fix: Path to php-cs-fixer cache
  .github/workflows/continuous-integration.yml
Labels: bug

#187 Enhancement: Use ergebnis/test-util instead of localheinz/test-util
  composer.json
  composer.lock
  test/AutoReview/SrcCodeTest.php
  test/Unit/ExampleTest.php
Labels: enhancement

#188 Fix: Do not use deprecated inputs
  .github/workflows/continuous-integration.yml
Labels: bug

#189 Enhancement: Use pcov instead of Xdebug
  .github/CONTRIBUTING.md
  .github/workflows/continuous-integration.yml
  Makefile
Labels: enhancement

#190 Fix: Path
  .github/workflows/continuous-integration.yml
Labels: bug

#191 Enhancement: Use ergebnis/phpstan-rules instead of localheinz/phpstan-rules
  composer.json
  composer.lock
Labels: enhancement

#192 Fix: Remove dependabot configuration without effect
  .dependabot/config.yml
Labels: bug

#193 Enhancement: Use actions/checkout@v2.0.0
  .github/workflows/continuous-integration.yml
Labels: enhancement

#194 Fix: Use tags to specify versions of actions to be used
  .github/workflows/continuous-integration.yml
Labels: bug

#195 Fix: Go back to updating dependencies live
  .dependabot/config.yml
Labels: bug

#196 Fix: Cache key
  .github/workflows/continuous-integration.yml
Labels: bug

#197 Enhancement: Update phpstan/phpstan and friends
  composer.json
  composer.lock
Labels: dependency

#198 Enhancement: Use webfactory/composer-require-checker instead of localheinz/composer-require-checker-action
  .github/workflows/continuous-integration.yml
  Makefile
Labels: enhancement

#199 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: bug

#200 Enhancement: Use ergebnis/composer-normalize instead of localheinz/composer-normalize
  composer.json
  composer.lock
Labels: dependency

#201 Fix: Step name
  .github/workflows/continuous-integration.yml
Labels: bug

#203 Enhancement: Extract environment variable REQUIRED_PHP_EXTENSIONS
  .github/workflows/continuous-integration.yml
Labels: enhancement

#204 Enhancement: Allow dependabot to automatically merge pull requests
  .dependabot/config.yml
  .github/settings.yml
Labels: enhancement

#205 Fix: Use single line for single chache restore key
  .github/workflows/continuous-integration.yml
Labels: bug

#206 Fix: Consistently quote strings
  .github/FUNDING.yml
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/stale.yml
Labels: bug

#207 Fix: Restriction
  .github/settings.yml
Labels: bug

#208 Fix: Restriction
  .github/settings.yml
Labels: bug

#209 Enhancement: Configure repository topics
  .github/settings.yml
Labels: enhancement

#210 Fix: Include hashes when specifying color codes
  .github/settings.yml
Labels: bug

#211 Fix: Use empty descriptions
  .github/settings.yml
Labels: bug

#212 Enhancement: Extract environment variables MIN_COVERED_MSI and MIN_MSI
  .github/workflows/continuous-integration.yml
  Makefile
Labels: enhancement

#213 Fix: Use consistent spacing
  .github/workflows/continuous-integration.yml
Labels: enhancement

#214 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: bug

#215 Enhancement: Update actions/stale
  .github/workflows/stale.yml
Labels: enhancement

#216 Enhancement: Require phpstan/phpstan-phpunit
  composer.json
  composer.lock
Labels: enhancement

#217 Fix: Do not bother checking iterable type
  phpstan.neon
Labels: bug

#218 Fix: Do not run builds for tags
  .github/workflows/continuous-integration.yml
Labels: bug

#219 Fix: Order
  .github/workflows/continuous-integration.yml
  .github/workflows/stale.yml
Labels: bug

#220 Enhancement: Automatically create release on tag
  .github/workflows/continuous-deployment.yml
  README.md
Labels: enhancement

#221 Enhancement: Determine raw tag
  .github/workflows/continuous-deployment.yml
Labels: enhancement

#222 Fix: Do not export phpstan-baseline.neon
  .gitattributes
Labels: bug

#224 Enhancement: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: enhancement

#223 Enhancement: Use vimeo/psalm in addition to phpstan/phpstan
  .gitattributes
  .github/CONTRIBUTING.md
  .github/workflows/continuous-integration.yml
  Makefile
  composer.json
  composer.lock
  phpstan-baseline.neon
  psalm-baseline.xml
  psalm.xml
Labels: enhancement
