Repository ergebnis/php-package-template, pull requests merged in 2020-04, with the labels that each got.

#380 Fix: Wait
  .github/workflows/integrate.yaml
Labels: bug, merge

#382 Fix: Approve pull request only on selected actions
  .github/workflows/integrate.yaml
Labels: bug, merge

#384 Fix: Add note about yamllint to CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: bug, merge

#388 Fix: Consistently quote strings in YAML files
  .yamllint.yaml
Labels: bug, merge

#392 Enhancement: Update actions/stale
  .github/workflows/prune.yaml
Labels: enhancement, merge

#395 Enhancement: Add label based on branch name
  .github/workflows/triage.yaml
Labels: merge

#396 Fix: Map
  .github/workflows/triage.yaml
Labels: bug, merge

#398 Fix: Require label job to pass
  .github/settings.yml
Labels: bug, merge

#399 Fix: Keep required jobs sorted by name
  .github/settings.yml
Labels: bug, merge

#400 Fix: Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: bug, merge

#402 Fix: Stop waiting
  .github/workflows/integrate.yaml
Labels: bug, merge

#403 Fix: cache key
  .github/workflows/integrate.yaml
Labels: bug
