Repository ergebnis/php-package-template, pull requests merged in 2020-01, with the labels that each got.

#225 Enhancement: Automatically approve pull requests updating development dependencies
  .dependabot/config.yml
  .github/workflows/approve.yml
Labels: enhancement

#226 Fix: Actually use matrix
  .github/workflows/continuous-integration.yml
Labels: bug

#227 Enhancement: Update ergebnis/php-cs-fixer-config
  composer.json
  composer.lock
Labels: dependency

#228 Fix: Configure platform
  composer.json
  composer.lock
Labels: bug

#235 Enhancement: Use different token
  .github/workflows/approve.yml
Labels: enhancement

#236 Fix: Approve pull request only when all checks have passed
  .github/workflows/approve.yml
  .github/workflows/continuous-integration.yml
Labels: bug

#237 Fix: Remove CODEOWNERS
  .github/CODEOWNERS
  .github/workflows/continuous-integration.yml
Labels: bug

#239 Fix: Use caret operator for ergebnis/php-cs-fixer-config
  composer.json
  composer.lock
Labels: bug

#241 Fix: Use AUTO_APPROVE_TOKEN
  .github/CODEOWNERS
  .github/workflows/continuous-integration.yml
Labels: bug

#242 Fix: Hide info level error messages emitted by vimeo/psalm
  .github/workflows/continuous-integration.yml
  Makefile
Labels: bug

#243 Enhancement: Add badge for type coverage
  .github/workflows/continuous-integration.yml
  README.md
Labels: enhancement

#245 Enhancement: Show statistics when running vimeo/psalm
  .github/workflows/continuous-integration.yml
  Makefile
Labels: enhancement

#249 Enhancement: Let @ergebnis-bot approve pull requests and create releases
  .dependabot/config.yml
  .github/settings.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
Labels: enhancement

#250 Enhancement: Let @ergebnis-bot close stale issues
  .github/workflows/stale.yml
Labels: enhancement

#252 Enhancement: Add @ergebnis-bot to CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#254 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: bug

#255 Fix: Remove default_assignes and default_reviewers configuration
  .dependabot/config.yml
Labels: bug

#257 Enhancement: Add archived setting
  .github/settings.yml
Labels: enhancement

#259 Fix: Add note about restrictions
  .github/settings.yml
Labels: bug

#260 Fix: Remove Patreon from FUNDING.yml
  .github/FUNDING.yml
Labels: bug

#261 Fix: Reduce number of items in list
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#263 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: bug

#264 Fix: Rename job
  .github/workflows/continuous-integration.yml
Labels: bug

#269 Enhancement: Delete branches on merge
  .github/settings.yml
Labels: enhancement

#270 Fix: Require Approve job to pass
  .github/settings.yml
Labels: bug

#244 Fix: Give badges a break
  README.md
Labels: bug

#271 Fix: Do not require Approve job to pass
  .github/settings.yml
Labels: bug

#272 Enhancement: Require and use ergebnis/license
  .github/workflows/license.yml
  .php_cs
  LICENSE.md
  README.md
  composer.json
  composer.lock
  src/Example.php
  test/AutoReview/SrcCodeTest.php
  test/Unit/ExampleTest.php
Labels: enhancement

#273 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: bug

#275 Fix: Require Review job to pass
  .github/settings.yml
Labels: bug

#274 Enhancement: Approve pull requests by @ergebnis-bot updating the license year
  .github/workflows/continuous-integration.yml
Labels: enhancement

#276 Fix: Do not require Review job to pass
  .github/settings.yml
Labels: bug

#277 Fix: Year
  .php_cs
  LICENSE.md
  src/Example.php
  test/AutoReview/SrcCodeTest.php
  test/Unit/ExampleTest.php
Labels: bug

#282 Fix: Wording
  .github/workflows/stale.yml
Labels: bug

#283 Fix: Wording
  README.md
Labels: bug

#284 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: bug

#285 Configure psalm's cache directory
  psalm.xml
Labels: bug

#287 Enhancement: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: enhancement
