Repository ergebnis/php-package-template, pull requests merged in 2020-05, with the labels that each got.

#406 Fix: Description
  Makefile
Labels: bug, merge

#409 Enhancement: Add link to list
  README.md
Labels: enhancement, merge

#411 Fix: Use caret operator
  composer.json
  composer.lock
Labels: bug, merge

#413 Enhancement: Normalize composer.json in coding-standards target
  .github/CONTRIBUTING.md
  Makefile
Labels: enhancement, merge

#419 Enhancement: Update actions/stale
  .github/workflows/prune.yaml
Labels: enhancement, merge

#422 Fix: Sort items
  infection.json
Labels: bug, merge

#423 Fix: Import parent namespace only
  .php_cs
  test/Unit/ExampleTest.php
Labels: bug, merge

#427 Enhancement: Update actions/github-script
  .github/workflows/integrate.yaml
  .github/workflows/triage.yaml
Labels: enhancement, merge

#430 Enhancement: Update actions/cache
  .github/workflows/integrate.yaml
  .github/workflows/renew.yaml
Labels: enhancement, merge

#428 Enhancement: Use event types instead of custom if
  .github/workflows/triage.yaml
Labels: enhancement
