Repository ergebnis/php-package-template, pull requests merged in 2020-02, with the labels that each got.

#291 Enhancement: Add mutation score badge
  .github/workflows/continuous-integration.yml
  README.md
  infection.json
Labels: enhancement

#292 Fix: Remove mutation score badge
  .github/workflows/continuous-integration.yml
  README.md
  infection.json
Labels: bug

#296 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: bug

#298 Fix: Update shivammathur/setup-php
  .github/workflows/license.yml
Labels: bug

#299 Fix: Link
  .github/CONTRIBUTING.md
Labels: bug

#302 Remove leading `#` of color labels
  .github/settings.yml
Labels: bug

#303 Bump actions/cache from 1.0.3 to 1.1.2
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: enhancement

#308 Enhancement: Update maglnet/composer-require-checker
  .github/workflows/continuous-integration.yml
  Makefile
Labels: dependency

#311 Enhancement: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: dependency

#312 Fix: Keep new lines in stale messages
  .github/workflows/stale.yml
Labels: bug

#315 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: bug

#316 Configure psalm error level
  psalm.xml
Labels: enhancement

#317 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: bug

#318 Enhancement: Determine composer cache directory
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: enhancement

#319 Fix: Update shivammathur/setup-php
  .github/workflows/continuous-integration.yml
Labels: bug

#321 Fix: Make it more obvious that we are dealing with directories
  .php_cs
  phpstan.neon
  psalm.xml
  test/AutoReview/SrcCodeTest.php
  test/Unit/phpunit.xml
Labels: bug

#322 make comments more explicit
  .github/workflows/continuous-integration.yml
Labels: enhancement

#323 Fix: Apply @staabm's patch everywhere
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
Labels: bug

#325 Enhancement: Reference rolling tags where available
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/license.yml
  .github/workflows/stale.yml
Labels: dependency
