Repository ergebnis/php-package-template, pull requests merged in 2020-03, with the labels that each got.

#327 Enhancement: Cache cache directory for phpstan/phpstan
  .github/workflows/continuous-integration.yml
Labels: enhancement

#331 Fix: Reference master branch
  README.md
Labels: bug

#332 Enhancement: Rename workflows
  .github/CONTRIBUTING.md
  .github/workflows/integrate.yml
  .github/workflows/prune.yml
  .github/workflows/release.yml
  .github/workflows/renew.yml
  README.md
Labels: enhancement

#335 Fix: Renew workflow should run on PHP 7.2
  .github/workflows/renew.yml
Labels: bug

#336 Fix: Workflow name
  .github/workflows/prune.yml
Labels: bug

#328 Fix: Do not cache cache directory for phpstan/phpstan
  .github/workflows/integrate.yml
Labels: bug

#337 Fix: List workflows in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: bug

#333 Fix: Reorder and add missing badges
  README.md
Labels: bug

#338 Fix: Use .yaml instead of .yml as file extension
  .dependabot/config.yaml
  .editorconfig
  .github/CONTRIBUTING.md
  .github/workflows/integrate.yaml
  .github/workflows/prune.yaml
  .github/workflows/release.yaml
  .github/workflows/renew.yaml
Labels: bug

#339 Enhancement: Lint YAML files
  .github/workflows/integrate.yaml
  .github/workflows/prune.yaml
  .github/workflows/release.yaml
  .github/workflows/renew.yaml
  .yamllint.yaml
  Makefile
Labels: enhancement

#342 Fix: Create directory for phpunit cache result file
  Makefile
Labels: bug

#343 Fix: Make it more obvious that we are dealing with directories
  phpstan.neon
Labels: bug

#346 Fix: support yml and yaml extension file in editor config
  .editorconfig
Labels: bug

#350 Enhancement: Cache cache directory for phpstan/phpstan
  .github/workflows/integrate.yaml
Labels: enhancement

#352 Fix: Update gr2m/create-or-update-pull-request-action
  .github/workflows/renew.yaml
Labels: bug

#354 Cache cache directory for vimeo/psalm
  .github/workflows/integrate.yaml
Labels: enhancement

#355 speed up vimeo/psalm
  .github/workflows/integrate.yaml
  Makefile
Labels: enhancement

#358 fix caching phpstan and psalm caches
  .github/workflows/integrate.yaml
Labels: bug

#357 Simplify hashFiles for composer.lock files
  .github/workflows/integrate.yaml
Labels: enhancement

#359 Fix: Do not check multi-line strings for indentation
  .yamllint.yaml
Labels: bug

#363 Enhancement: Let @ergebnis-bot review, approve, and merge pull requests
  .dependabot/config.yaml
  .github/CODEOWNERS
  .github/workflows/integrate.yaml
Labels: enhancement

#364 Enhancement: Check in composer-require-checker to avoid using Docker
  .gitattributes
  .github/workflows/integrate.yaml
  Makefile
  phive.xml
  tools/composer-require-checker
Labels: enhancement

#365 Fix: Merge method
  .github/workflows/integrate.yaml
Labels: bug

#366 Fix: Remove dependabot from restriction exclusions
  .github/settings.yml
Labels: bug

#367 Fix: Add @ergebnis-bot to CODEOWNERS
  .github/CODEOWNERS
Labels: bug

#368 Fix: CODEOWNERS
  .github/CODEOWNERS
Labels: bug

#369 Fix: Exclude dependency-analysis from it target
  .github/CONTRIBUTING.md
  Makefile
Labels: bug

#370 Fix: Ignore .notes directory
  .gitignore
  .php_cs
  .yamllint.yaml
Labels: bug

#371 Fix: Remove placeholder
  phpstan.neon
Labels: bug

#372 Fix: Actor is dependabot-preview[bot]
  .github/workflows/integrate.yaml
Labels: bug

#373 Enhancement: Let @ergebnis-bot merge pull request when it has merge label
  .github/settings.yml
  .github/workflows/integrate.yaml
Labels: enhancement, merge

#374 Fix: Merge jobs
  .github/settings.yml
  .github/workflows/integrate.yaml
Labels: bug, merge

#375 Fix: Use multiple lines for condition
  .github/workflows/integrate.yaml
Labels: bug, merge

#376 Fix: Request review first
  .github/workflows/integrate.yaml
Labels: bug, merge
